### ISSUE TITLE
META: Unify workflow decisions between example repositories

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/example-drops-8-composer#111]
See https://github.com/pantheon-systems/example-drops-8-composer/pull/107 for background.

- [ ] Run or skip tests on non-pull-request builds: https://github.com/pantheon-systems/example-wordpress-composer/issues/40
- [ ] Backup site before tests, restore after tests
- [ ] Run `terminus wp` or `terminus drush` prior to starting behat tests
- [ ] Delete and re-create test admin user prior to starting behat tests
